[tools]
"aqua:golangci/golangci-lint" = "2.10.1"

[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tasks.test]
description = "Run tests"
run = "go tool gotest.tools/gotestsum ./..."

[tasks.ci]
description = "Run CI tasks"
depends = ["lint", "test"]
